// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tedu.Server.Status.DataAccess;

namespace Tedu.Server.Status.DataAccess.Migrations.Migrations
{
    [DbContext(typeof(TeduStatusDbContext))]
    [Migration("20191004173818_Add-Backup-table")]
    partial class AddBackuptable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Tedu.Server.Status.DataAccess.Entities.Backup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn);

                    b.Property<int>("BackupDurationCopySeconds")
                        .HasColumnName("backupdurationcopyseconds");

                    b.Property<int>("BackupDurationTotalSeconds")
                        .HasColumnName("backupdurationtotalseconds");

                    b.Property<int>("BackupsAmount")
                        .HasColumnName("backupsamount");

                    b.Property<DateTime>("CreatedDateTimeUtc")
                        .HasColumnName("createddatetimeutc");

                    b.Property<int>("DiskFreeBytes")
                        .HasColumnName("diskfreebytes");

                    b.Property<int>("DiskUsedBytes")
                        .HasColumnName("diskusedbytes");

                    b.Property<bool>("IsStatusOk")
                        .HasColumnName("isstatusok");

                    b.Property<DateTime>("LastBackupEndDateTimeUtc")
                        .HasColumnName("lastbackupenddatetimeutc");

                    b.Property<int>("LastBackupSizeBytes")
                        .HasColumnName("lastbackupsizebytes");

                    b.Property<DateTime>("LastBackupStartDateTimeUtc")
                        .HasColumnName("lastbackupstartdatetimeutc");

                    b.Property<DateTime>("OldestBackupEndDateTimeUtc")
                        .HasColumnName("oldestbackupenddatetimeutc");

                    b.Property<int>("ServerId")
                        .HasColumnName("serverid");

                    b.HasKey("Id")
                        .HasName("pk_backup");

                    b.ToTable("backup");
                });

            modelBuilder.Entity("Tedu.Server.Status.DataAccess.Entities.Probe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn);

                    b.Property<DateTime>("CheckedDateTimeUtc")
                        .HasColumnName("checkeddatetimeutc");

                    b.Property<int>("Result")
                        .HasColumnName("result");

                    b.Property<int>("ServerId")
                        .HasColumnName("serverid");

                    b.Property<int>("Type")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_probe");

                    b.HasIndex("ServerId")
                        .HasName("ix_probe_serverid");

                    b.ToTable("probe");
                });

            modelBuilder.Entity("Tedu.Server.Status.DataAccess.Entities.Server", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn);

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnName("host");

                    b.HasKey("Id")
                        .HasName("pk_server");

                    b.HasIndex("Host")
                        .IsUnique()
                        .HasName("ix_server_host");

                    b.ToTable("server");
                });

            modelBuilder.Entity("Tedu.Server.Status.DataAccess.Entities.Probe", b =>
                {
                    b.HasOne("Tedu.Server.Status.DataAccess.Entities.Server", "Server")
                        .WithMany("Probes")
                        .HasForeignKey("ServerId")
                        .HasConstraintName("fk_probe_server_serverid")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
